### ISSUE TITLE
cannot unescape "%3cimg%3e冷却缩减以及30%回复量"

### ISSUE THREAD

**Issue by figozhu** [XadillaX/true-html-escape#2]
using php urldecode this string woulde be "<img>冷却缩减以及30%回复量"

**Comment by XadillaX** [comment]
不好意思，这个包是 `html-escape` 而不是 `urlencode`。如果确实需要这个功能，请使用 Javascript 原生的 `unescape()` 函数：

```javascript
unescape("%3cimg%3e冷却缩减以及30%回复量"); // <img>冷却缩减以及30%回复量
```
